# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PokerTrain' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PokerTrain
  pod 'SnapKit'
 pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Messaging'
pod 'Firebase/RemoteConfig'
pod 'YandexMobileMetrica'
end
